In [1]:
import pandas as pd
import numpy as np

In [5]:
dd=pd.read_csv("E:\streamlit\Streamlit_programs\PROJECTS\Tamil_Nadu_AE.csv")
dd

C:\Users\Admin\AppData\Local\Temp\ipykernel_1056\164283602.py:1: DtypeWarning: Columns (13,18,19,38,39,40,41,42,43,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  dd=pd.read_csv("E:\streamlit\Streamlit_programs\PROJECTS\Tamil_Nadu_AE.csv")

,State_Name,Assembly_No,Constituency_No,Year,month,DelimID,Poll_No,Position,Candidate,Sex,...,No_Terms,Turncoat,Incumbent,Recontest,MyNeta_education,TCPD_Prof_Main,TCPD_Prof_Main_Desc,TCPD_Prof_Second,TCPD_Prof_Second_Desc,Election_Type
0,Tamil_Nadu,12,1,2021,5.0,4,0,1,GOVINDARAJAN T.J,M,...,1.0,False,False,False,10th Pass,Business,NaN,NaN,NaN,State Assembly Election (AE)
1,Tamil_Nadu,12,1,2021,5.0,4,0,2,PRAKASH M,M,...,0.0,False,False,False,10th Pass,Salaried Work or Employed,Qualified Professional,NaN,NaN,State Assembly Election (AE)
2,Tamil_Nadu,12,1,2021,5.0,4,0,3,USHA,F,...,0.0,False,False,False,8th Pass,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
3,Tamil_Nadu,12,1,2021,5.0,4,0,4,DILLIY K.M,M,...,0.0,False,False,False,8th Pass,Other,NaN,NaN,NaN,State Assembly Election (AE)
4,Tamil_Nadu,12,1,2021,5.0,4,0,5,None Of The Above,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30723,Tamil_Nadu,1,233,1971,3.0,2,0,3,PACKIA DAS D.,M,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
30724,Tamil_Nadu,1,233,1971,3.0,2,0,4,ALVIN P.,M,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
30725,Tamil_Nadu,1,234,1971,3.0,2,0,1,DENNIS N.,M,...,1.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
30726,Tamil_Nadu,1,234,1971,3.0,2,0,2,RUSSELRAJ C.,M,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
30727,Tamil_Nadu,1,234,1971,3.0,2,0,3,JACINTH MENDEZ S.,M,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)

In [299]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30728 entries, 0 to 30727
Data columns (total 47 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State_Name              30728 non-null  object
 1   Assembly_No             30728 non-null  int64
 2   Constituency_No         30728 non-null  int64
 3   Year                    30728 non-null  int64
 4   month                   29521 non-null  float64
 5   DelimID                 30728 non-null  int64
 6   Poll_No                 30728 non-null  int64
 7   Position                30728 non-null  int64
 8   Candidate               30728 non-null  object
 9   Sex                     29886 non-null  object
 10  Party                   30706 non-null  object
 11  Votes                   30728 non-null  int64
 12  Age                     13489 non-null  float64
 13  Candidate_Type          9491 non-null   object
 14  Valid_Votes             30728 non-null  int64
 15  Electors                30728 non-null  int64
 16  Constituency_Name       30728 non-null  object
 17  Constituency_Type       30728 non-null  object
 18  District_Name           11550 non-null  object
 19  Sub_Region              11550 non-null  object
 20  N_Cand                  30728 non-null  int64
 21  Turnout_Percentage      30728 non-null  float64
 22  Vote_Share_Percentage   30728 non-null  float64
 23  Deposit_Lost            30240 non-null  object
 24  Margin                  30728 non-null  int64
 25  Margin_Percentage       30728 non-null  float64
 26  ENOP                    30728 non-null  float64
 27  pid                     30240 non-null  object
 28  Party_Type_TCPD         25913 non-null  object
 29  Party_ID                30682 non-null  float64
 30  last_poll               30728 non-null  bool
 31  Contested               30240 non-null  float64
 32  Last_Party              4077 non-null   object
 33  Last_Party_ID           4067 non-null   float64
 34  Last_Constituency_Name  4077 non-null   object
 35  Same_Constituency       4079 non-null   object
 36  Same_Party              4079 non-null   object
 37  No_Terms                30240 non-null  float64
 38  Turncoat                30240 non-null  object
 39  Incumbent               30240 non-null  object
 40  Recontest               30240 non-null  object
 41  MyNeta_education        7373 non-null   object
 42  TCPD_Prof_Main          7562 non-null   object
 43  TCPD_Prof_Main_Desc     2502 non-null   object
 44  TCPD_Prof_Second        503 non-null    object
 45  TCPD_Prof_Second_Desc   123 non-null    object
 46  Election_Type           30728 non-null  object
dtypes: bool(1), float64(10), int64(11), object(25)
memory usage: 10.8+ MB

In [111]:
dd.columns

Index(['State_Name', 'Assembly_No', 'Constituency_No', 'Year', 'month',
       'DelimID', 'Poll_No', 'Position', 'Candidate', 'Sex', 'Party', 'Votes',
       'Age', 'Candidate_Type', 'Valid_Votes', 'Electors', 'Constituency_Name',
       'Constituency_Type', 'District_Name', 'Sub_Region', 'N_Cand',
       'Turnout_Percentage', 'Vote_Share_Percentage', 'Deposit_Lost', 'Margin',
       'Margin_Percentage', 'ENOP', 'pid', 'Party_Type_TCPD', 'Party_ID',
       'last_poll', 'Contested', 'Last_Party', 'Last_Party_ID',
       'Last_Constituency_Name', 'Same_Constituency', 'Same_Party', 'No_Terms',
       'Turncoat', 'Incumbent', 'Recontest', 'MyNeta_education',
       'TCPD_Prof_Main', 'TCPD_Prof_Main_Desc', 'TCPD_Prof_Second',
       'TCPD_Prof_Second_Desc', 'Election_Type'],
      dtype='object')

In [129]:
dd4_4 = dd[['Constituency_No', 'Constituency_Name', 'Year', 'Party', 'Valid_Votes']]
d5 = dd4_4.groupby(['Constituency_No', 'Constituency_Name', 'Year'])['Valid_Votes'].unique().reset_index()
d5['Valid_Votes']=d5['Valid_Votes'].str[0]
d6 = d5[d5['Year'] == 2006]

In [130]:
d6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 235 entries, 10 to 2867
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Constituency_No    235 non-null    int64
 1   Constituency_Name  235 non-null    object
 2   Year               235 non-null    int64
 3   Valid_Votes        235 non-null    int64
dtypes: int64(3), object(1)
memory usage: 9.2+ KB

In [131]:
d6

      Constituency_No        Constituency_Name  Year  Valid_Votes
10                  1                ROYAPURAM  2006        95090
20                  2                  HARBOUR  2006        60005
32                  3  DR. RADHAKRISHNAN NAGAR  2006       167730
44                  4                PARK TOWN  2006        72915
56                  5                 PERAMBUR  2006       182379
...               ...                      ...   ...          ...
2818              230                 COLACHEL  2006       107772
2833              231          PADMANABHAPURAM  2006        97273
2845              232              THIRUVATTAR  2006       110775
2855              233              VILAVANCODE  2006       120076
2867              234                KILLIYOOR  2006        92455

[235 rows x 4 columns]

In [167]:
d6

      Constituency_No        Constituency_Name  Year  Valid_Votes
10                  1                Royapuram  2006        95090
20                  2                  Harbour  2006        60005
32                  3  Dr. Radhakrishnan Nagar  2006       167730
44                  4                Park Town  2006        72915
56                  5                 Perambur  2006       182379
...               ...                      ...   ...          ...
2818              230                 Colachel  2006       107772
2833              231          Padmanabhapuram  2006        97273
2845              232              Thiruvattar  2006       110775
2855              233              Vilavancode  2006       120076
2867              234                Killiyoor  2006        92455

[235 rows x 4 columns]

In [132]:
d6[d6['Constituency_Name']=='TIRUCHENDUR']

      Constituency_No Constituency_Name  Year  Valid_Votes
2758              225       TIRUCHENDUR  2006       111580

In [133]:
import json
j=json.load(open("E:\streamlit\Streamlit_programs\PROJECTS\TAMIL NADU_ASSEMBLY.geojson",'r'))

In [134]:
j.keys()

dict_keys(['type', 'crs', 'features'])

In [135]:
j['features'][0]['properties'].update({"vote":9090})

In [136]:
j['features'][0]['properties']

{'FID': 3180,
 'OBJECTID': 3205,
 'ST_CODE': '33',
 'ST_NAME': 'TAMIL NADU',
 'DT_CODE': '01',
 'DIST_NAME': 'THIRUVALLUR',
 'AC_NO': 2,
 'AC_NAME': 'Ponneri (SC)',
 'PC_NO': 1,
 'PC_NAME': 'TIRUVALLUR (SC)',
 'PC_ID': 3301,
 'STATUS': ' ',
 'Shape_Leng': 1.43096669428,
 'Shape_Area': 0.0496048544961,
 'dtcode11': '602',
 'dtname11': 'Thiruvallur',
 'vote': 9090}

In [144]:
cno=d6['Constituency_No'].tolist()
cvote=d6['Valid_Votes'].tolist()

In [145]:
dic={}
for i,j1 in zip(cno,cvote):
    dic.update({i:j1})

In [146]:
dic

{1: 95090,
 2: 60005,
 3: 167730,
 4: 72915,
 5: 182379,
 6: 191680,
 7: 79326,
 8: 216659,
 9: 152632,
 10: 108291,
 11: 67082,
 12: 85504,
 13: 147345,
 14: 164295,
 15: 156263,
 16: 175229,
 17: 341402,
 18: 611084,
 19: 284403,
 20: 561888,
 21: 162708,
 22: 127475,
 23: 117418,
 24: 109003,
 25: 144596,
 26: 172723,
 27: 160042,
 28: 203991,
 29: 133732,
 30: 122687,
 31: 126680,
 32: 140646,
 33: 138112,
 34: 168313,
 35: 123707,
 36: 151130,
 37: 121338,
 38: 131491,
 39: 131360,
 40: 154916,
 41: 147764,
 42: 124842,
 43: 143976,
 44: 149893,
 45: 142192,
 46: 124456,
 47: 131556,
 48: 135359,
 49: 141134,
 50: 135508,
 51: 123414,
 52: 121231,
 53: 123907,
 54: 129946,
 55: 118735,
 56: 140884,
 57: 139441,
 58: 154600,
 59: 128303,
 60: 125832,
 61: 149061,
 62: 124365,
 63: 140286,
 64: 143148,
 65: 123708,
 66: 127834,
 67: 111245,
 68: 111066,
 69: 151731,
 70: 142349,
 71: 128194,
 72: 132298,
 73: 144844,
 74: 215406,
 75: 123888,
 76: 141173,
 77: 140271,
 78: 143663,
 79: 155411,
 80: 126784,
 81: 150902,
 82: 147708,
 83: 149932,
 84: 138183,
 85: 141757,
 86: 134357,
 87: 113626,
 88: 156561,
 89: 180545,
 90: 212846,
 91: 164238,
 92: 118370,
 93: 131943,
 94: 137750,
 95: 129240,
 96: 143999,
 97: 122862,
 98: 212068,
 99: 144691,
 100: 169848,
 101: 151546,
 102: 134476,
 103: 296863,
 104: 240267,
 105: 100669,
 106: 109103,
 107: 246121,
 108: 117812,
 109: 135722,
 110: 86321,
 111: 143593,
 112: 123871,
 113: 117618,
 114: 114351,
 115: 167080,
 116: 244194,
 117: 123559,
 118: 146507,
 119: 137506,
 120: 214918,
 121: 126612,
 122: 111198,
 123: 121516,
 124: 128086,
 125: 121465,
 126: 95666,
 127: 95797,
 128: 143352,
 129: 120386,
 130: 118896,
 131: 137287,
 132: 136690,
 133: 117347,
 134: 117390,
 135: 134304,
 136: 97990,
 137: 120248,
 138: 92503,
 139: 122838,
 140: 112702,
 141: 274014,
 142: 131030,
 143: 90897,
 144: 95244,
 145: 286907,
 146: 135283,
 147: 133614,
 148: 152748,
 149: 143432,
 150: 149370,
 151: 100783,
 152: 170676,
 153: 126049,
 154: 135080,
 155: 138070,
 156: 123642,
 157: 125957,
 158: 153726,
 159: 132167,
 160: 133863,
 161: 121148,
 162: 132460,
 163: 113460,
 164: 135031,
 165: 193841,
 166: 86797,
 167: 149931,
 168: 189750,
 169: 123817,
 170: 120015,
 171: 115612,
 172: 129123,
 173: 127511,
 174: 135462,
 175: 125060,
 176: 132984,
 177: 137841,
 178: 137898,
 179: 125918,
 180: 129781,
 181: 128638,
 182: 149991,
 183: 123038,
 184: 114898,
 185: 123180,
 186: 109960,
 187: 125038,
 188: 134700,
 189: 117986,
 190: 148090,
 191: 152502,
 192: 152986,
 193: 144402,
 194: 107312,
 195: 131432,
 196: 117605,
 197: 97465,
 198: 115675,
 199: 109458,
 200: 112600,
 201: 144149,
 202: 119431,
 203: 103706,
 204: 115875,
 205: 149088,
 206: 130333,
 207: 183001,
 208: 135549,
 209: 148122,
 210: 97171,
 211: 98404,
 212: 114478,
 213: 125468,
 214: 113705,
 215: 120446,
 216: 139570,
 217: 135294,
 218: 142908,
 219: 148900,
 220: 110996,
 221: 108059,
 222: 104665,
 223: 113584,
 224: 87035,
 225: 111580,
 226: 93643,
 227: 157446,
 228: 126225,
 229: 119334,
 230: 107772,
 231: 97273,
 232: 110775,
 233: 120076,
 234: 92455}

In [147]:
for jj in cno:
    for ii in range(0,234):
        if j['features'][ii]['properties']['AC_NO']==jj:
            j['features'][ii]['properties'].update({'Vaild_Vote':dic[jj]})

In [143]:
j['features'][4]['properties']

{'FID': 3184,
 'OBJECTID': 3209,
 'ST_CODE': '33',
 'ST_NAME': 'TAMIL NADU',
 'DT_CODE': '01',
 'DIST_NAME': 'THIRUVALLUR',
 'AC_NO': 5,
 'AC_NAME': 'Poonamallee (SC)',
 'PC_NO': 1,
 'PC_NAME': 'TIRUVALLUR (SC)',
 'PC_ID': 3301,
 'STATUS': ' ',
 'Shape_Leng': 1.61630111579,
 'Shape_Area': 0.027629038174,
 'dtcode11': '602',
 'dtname11': 'Thiruvallur'}

In [142]:
len(j['features'])

235

In [165]:
j['features'][217]['properties']

{'FID': 3397,
 'OBJECTID': 3422,
 'ST_CODE': '33',
 'ST_NAME': 'TAMIL NADU',
 'DT_CODE': '29',
 'DIST_NAME': 'TIRUNELVELI',
 'AC_NO': 221,
 'AC_NAME': 'Kadayanallur',
 'PC_NO': 37,
 'PC_NAME': 'TENKASI (SC)',
 'PC_ID': 3337,
 'STATUS': ' ',
 'Shape_Leng': 1.30564763815,
 'Shape_Area': 0.0423231950385,
 'dtcode11': '628',
 'dtname11': 'Tirunelveli',
 'Vaild_Vote': 108059}

In [126]:
#decending order
li=[8,9,45,90]
for i in range(len(li)):
    for j in range(len(li)):
        if li[i]>li[j]:
            temp=li[i]
            li[i]=li[j]
            li[j]=temp

In [127]:
li

[90, 45, 9, 8]

In [128]:
li[1]

45

In [168]:
ds=dd[dd['Party']=='ADMK']

In [169]:
ds

,State_Name,Assembly_No,Constituency_No,Year,month,DelimID,Poll_No,Position,Candidate,Sex,...,No_Terms,Turncoat,Incumbent,Recontest,MyNeta_education,TCPD_Prof_Main,TCPD_Prof_Main_Desc,TCPD_Prof_Second,TCPD_Prof_Second_Desc,Election_Type
14,Tamil_Nadu,12,2,2021,5.0,4,0,2,BALARAMAN. P,M,...,1.0,False,True,True,Post Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
25,Tamil_Nadu,12,3,2021,5.0,4,0,2,G.Hari,M,...,1.0,False,False,False,Post Graduate,Liberal Profession or Professional,Lawyer,NaN,NaN,State Assembly Election (AE)
40,Tamil_Nadu,12,4,2021,5.0,4,0,2,"RAMANAH, BE VEE",M,...,0.0,False,False,False,Others,Business,NaN,NaN,NaN,State Assembly Election (AE)
67,Tamil_Nadu,12,6,2021,5.0,4,0,2,Pandiarajan K,M,...,2.0,False,True,True,Post Graduate,Liberal Profession or Professional,Consultant,NaN,NaN,State Assembly Election (AE)
88,Tamil_Nadu,12,7,2021,5.0,4,0,2,BENJAMIN.P,M,...,1.0,False,True,True,Graduate,Politics,Party Worker,Agriculture,NaN,State Assembly Election (AE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20394,Tamil_Nadu,7,147,1999,NaN,3,1,1,Viswanathan.R,M,...,1.0,True,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
20404,Tamil_Nadu,7,62,2000,NaN,3,1,2,Velayutham M.,M,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
20411,Tamil_Nadu,7,167,2000,NaN,3,1,2,Rathinavel T.,M,...,1.0,False,False,True,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
20423,Tamil_Nadu,7,193,2000,NaN,3,1,2,Raja Paramasivam,M,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)
22891,Tamil_Nadu,6,13,1994,NaN,3,1,1,V. Balasubramaniyan,NaN,...,1.0,False,False,False,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)

In [170]:
party_table=dd[dd['Party']=='DMK']
dd4_41 = party_table[['Constituency_No', 'Constituency_Name', 'Year', 'Party', 'Votes']]
d51=dd4_41.groupby(['Constituency_No', 'Constituency_Name', 'Year'])['Votes'].sum().reset_index()
d61 = d51[d51['Year'] == 2021]

In [171]:
d61

      Constituency_No Constituency_Name  Year   Votes
1                   1      GUMMIDIPUNDI  2021  126452
27                  3         TIRUTTANI  2021  120314
39                  4       THIRUVALLUR  2021  107709
50                  5       POONAMALLEE  2021  149578
52                  6             AVADI  2021  150287
...               ...               ...   ...     ...
2066              226     PALAYAMCOTTAI  2021   89117
2091              228        RADHAPURAM  2021   82331
2094              229     KANNIYAKUMARI  2021   93532
2111              230         NAGERCOIL  2021   77135
2118              232   PADMANABHAPURAM  2021   87744

[188 rows x 4 columns]

{'FID': 3180,
 'OBJECTID': 3205,
 'ST_CODE': '33',
 'ST_NAME': 'TAMIL NADU',
 'DT_CODE': '01',
 'DIST_NAME': 'THIRUVALLUR',
 'AC_NO': 2,
 'AC_NAME': 'Ponneri (SC)',
 'PC_NO': 1,
 'PC_NAME': 'TIRUVALLUR (SC)',
 'PC_ID': 3301,
 'STATUS': ' ',
 'Shape_Leng': 1.43096669428,
 'Shape_Area': 0.0496048544961,
 'dtcode11': '602',
 'dtname11': 'Thiruvallur',
 'vote': 9090,
 'Vaild_Vote': 60005}

In [186]:
import json
j=json.load(open("E:\streamlit\Streamlit_programs\PROJECTS\TAMIL NADU_ASSEMBLY.geojson",'r'))

In [187]:
j['features'][0]['properties']

{'FID': 3180,
 'OBJECTID': 3205,
 'ST_CODE': '33',
 'ST_NAME': 'TAMIL NADU',
 'DT_CODE': '01',
 'DIST_NAME': 'THIRUVALLUR',
 'AC_NO': 2,
 'AC_NAME': 'Ponneri (SC)',
 'PC_NO': 1,
 'PC_NAME': 'TIRUVALLUR (SC)',
 'PC_ID': 3301,
 'STATUS': ' ',
 'Shape_Leng': 1.43096669428,
 'Shape_Area': 0.0496048544961,
 'dtcode11': '602',
 'dtname11': 'Thiruvallur'}

In [290]:
json_data = json.load(open("E:\streamlit\Streamlit_programs\PROJECTS\TAMIL NADU_DISTRICTS.geojson", 'r'))

In [230]:
json_data['features'][1]['properties']

{'OBJECTID': 87,
 'dtname': 'Tiruppattur',
 'stname': 'TAMIL NADU',
 'stcode11': '33',
 'dtcode11': '788',
 'year_stat': '201920',
 'test': 0,
 'Dist_LGD': 732,
 'State_LGD': 33,
 'Shape_Leng': 333906.473792,
 'Shape.STArea()': 0.17674474989757982,
 'Shape.STLength()': 2.9609432648090515}

In [231]:
# Assuming json_data is a dictionary loaded from your JSON file
li=[]
for feature in json_data['features'][0:]:
    dtcode11 = feature['properties']['dtcode11']
    li.append(dtcode11)
print(len(li))
print(li)

37
['602', '788', '603', '787', '631', '606', '630', '608', '610', '611', '609', '615', '632', '614', '616', '633', '620', '613', '619', '612', '623', '624', '625', '628', '627', '629', '607', '617', '618', '621', '626', '622', '786', '790', '605', '789', '604']

In [232]:
li2=list(dd['District_Name'].unique())

In [233]:
len(li2)

33

In [234]:
b = dd[['Constituency_Name', 'District_Name', 'Year', 'Valid_Votes']]
b1 = b.groupby(['Constituency_Name', 'District_Name', 'Year'])['Valid_Votes'].unique().reset_index()
b2 = b1.groupby(['District_Name', 'Year'])['Valid_Votes'].sum().reset_index()

b2_year = b2[b2['Year'] == 2021]

In [235]:
b2_year

       District_Name  Year Valid_Votes
2           ARIYALUR  2021    [441593]
7            CHENNAI  2021   [2416815]
10        COIMBATORE  2021   [2031209]
13         CUDDALORE  2021   [1662957]
17        DHARMAPURI  2021   [1053792]
21          DINDIGUL  2021   [1455327]
24             ERODE  2021   [1500895]
29       KANCHIPURAM  2021   [2711269]
32     KANNIYAKUMARI  2021   [1099938]
36             KARUR  2021    [762782]
40       KRISHNAGIRI  2021   [1244916]
44           MADURAI  2021   [1920405]
47      NAGAPATTINAM  2021   [1018418]
50          NAMAKKAL  2021   [1173189]
54          NILGIRIS  2021    [677582]
57        PERAMBALUR  2021    [459905]
61       PUDUKKOTTAI  2021   [1044856]
65    RAMANATHAPURAM  2021    [819284]
69             SALEM  2021   [2414875]
73         SIVAGANGA  2021    [828327]
77         THANJAVUR  2021   [1539171]
81             THENI  2021    [828407]
85       THOOTHUKUDI  2021   [1053266]
89   TIRUCHIRAPPALLI  2021   [1742011]
94       TIRUNELVELI  2021   [1898370]
97           TIRUPUR  2021   [1505917]
101       TIRUVALLUR  2021   [2460818]
104   TIRUVANNAMALAI  2021   [1656974]
108        TIRUVARUR  2021    [809349]
112          VELLORE  2021   [2512641]
116       VILLUPURAM  2021   [2244928]
120     VIRUDHUNAGAR  2021   [1246306]

In [236]:
li3=list(dd['District_Name'].unique())

In [237]:
len(li3)

33

In [297]:
li3=['Chengalpattu','Kallakurichchi','Ranipet','Tenkasi','Tiruppattur']
# Replace 'your_key_to_clear' with the actual key you want to clear
#key_to_clear = 'dtname'
for li in li3:
    for feature in json_data.get('features', []):
        properties = feature.get('properties', {})
        dt=properties.get('dtname', {})
        print(dt)
    # Check if the key exists before attempting to clear it
        if dt in li:
            feature.pop('properties')

# Now 'dtname' key is removed from all 'properties' dictionaries

Tiruvallur
{}

TypeError: 'in <string>' requires string as left operand, not dict

In [295]:
for feature in json_data['features'][0:]:
    dtcode11 = feature['properties']['dtname']
    print(dtcode11)

Tiruvallur

KeyError: 'properties'

In [300]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30728 entries, 0 to 30727
Data columns (total 47 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State_Name              30728 non-null  object
 1   Assembly_No             30728 non-null  int64
 2   Constituency_No         30728 non-null  int64
 3   Year                    30728 non-null  int64
 4   month                   29521 non-null  float64
 5   DelimID                 30728 non-null  int64
 6   Poll_No                 30728 non-null  int64
 7   Position                30728 non-null  int64
 8   Candidate               30728 non-null  object
 9   Sex                     29886 non-null  object
 10  Party                   30706 non-null  object
 11  Votes                   30728 non-null  int64
 12  Age                     13489 non-null  float64
 13  Candidate_Type          9491 non-null   object
 14  Valid_Votes             30728 non-null  int64
 15  Electors                30728 non-null  int64
 16  Constituency_Name       30728 non-null  object
 17  Constituency_Type       30728 non-null  object
 18  District_Name           11550 non-null  object
 19  Sub_Region              11550 non-null  object
 20  N_Cand                  30728 non-null  int64
 21  Turnout_Percentage      30728 non-null  float64
 22  Vote_Share_Percentage   30728 non-null  float64
 23  Deposit_Lost            30240 non-null  object
 24  Margin                  30728 non-null  int64
 25  Margin_Percentage       30728 non-null  float64
 26  ENOP                    30728 non-null  float64
 27  pid                     30240 non-null  object
 28  Party_Type_TCPD         25913 non-null  object
 29  Party_ID                30682 non-null  float64
 30  last_poll               30728 non-null  bool
 31  Contested               30240 non-null  float64
 32  Last_Party              4077 non-null   object
 33  Last_Party_ID           4067 non-null   float64
 34  Last_Constituency_Name  4077 non-null   object
 35  Same_Constituency       4079 non-null   object
 36  Same_Party              4079 non-null   object
 37  No_Terms                30240 non-null  float64
 38  Turncoat                30240 non-null  object
 39  Incumbent               30240 non-null  object
 40  Recontest               30240 non-null  object
 41  MyNeta_education        7373 non-null   object
 42  TCPD_Prof_Main          7562 non-null   object
 43  TCPD_Prof_Main_Desc     2502 non-null   object
 44  TCPD_Prof_Second        503 non-null    object
 45  TCPD_Prof_Second_Desc   123 non-null    object
 46  Election_Type           30728 non-null  object
dtypes: bool(1), float64(10), int64(11), object(25)
memory usage: 10.8+ MB

In [372]:
d1=dd.groupby(['Constituency_Name'])['District_Name'].unique().reset_index()
d1['District_Name']=d1['District_Name'].str[0]
d1

    Constituency_Name District_Name
0         ACHARAPAKAM           NaN
1        ACHARAPAKKAM           NaN
2           ADUTHURAI           NaN
3             ALANDUR   KANCHIPURAM
4            ALANGUDI   PUDUKKOTTAI
..                ...           ...
387     VRIDDHACHALAM     CUDDALORE
388      VRIDHACHALAM           NaN
389         WANDIWASH           NaN
390      WASHERMANPET           NaN
391           YERCAUD         SALEM

[392 rows x 2 columns]

In [366]:
di={}
for k,kk in zip(d1['Constituency_Name'],d1['District_Name']):
    di.update({k:kk})
di.update({'PARK TOWN':'CHENNAI','PURASAWALKAM':'CHENNAI'})

In [367]:
di

{'ALANDUR': 'KANCHIPURAM',
 'ALANGUDI': 'PUDUKKOTTAI',
 'ALANGULAM': 'TIRUNELVELI',
 'AMBASAMUDRAM': 'TIRUNELVELI',
 'AMBATTUR': 'TIRUVALLUR',
 'AMBUR': 'VELLORE',
 'ANAIKATTU': 'VELLORE',
 'ANDIPATTI': 'THENI',
 'ANNA NAGAR': 'CHENNAI',
 'ANTHIYUR': 'ERODE',
 'ARAKONAM': 'VELLORE',
 'ARANI': 'TIRUVANNAMALAI',
 'ARANTANGI': 'PUDUKKOTTAI',
 'ARAVAKURICHI': 'KARUR',
 'ARCOT': 'VELLORE',
 'ARIYALUR': 'ARIYALUR',
 'ARUPPUKOTTAI': 'VIRUDHUNAGAR',
 'ATHOOR': 'DINDIGUL',
 'ATTUR': 'SALEM',
 'AVADI': 'TIRUVALLUR',
 'AVANASHI': 'TIRUPUR',
 'BARGUR': 'KRISHNAGIRI',
 'BHAVANI': 'ERODE',
 'BHAVANISAGAR': 'TIRUPUR',
 'BHUVANAGIRI': 'CUDDALORE',
 'BODINAYAKANUR': 'THENI',
 'CHENGALPATTU': 'KANCHIPURAM',
 'CHENGAM': 'TIRUVANNAMALAI',
 'CHEPAUK-THIRUVALLIKENI': 'CHENNAI',
 'CHEYYAR': 'TIRUVANNAMALAI',
 'CHEYYUR': 'KANCHIPURAM',
 'CHIDAMBARAM': 'CUDDALORE',
 'COIMBATORE NORTH': 'COIMBATORE',
 'COIMBATORE SOUTH': 'COIMBATORE',
 'COLACHEL': 'KANNIYAKUMARI',
 'COONOOR': 'TIRUPUR',
 'CUDDALORE': 'CUDDALORE',
 'CUMBUM': 'THENI',
 'DHARAPURAM': 'ERODE',
 'DHARMAPURI': 'DHARMAPURI',
 'DINDIGUL': 'DINDIGUL',
 'DR. RADHAKRISHNAN NAGAR': 'CHENNAI',
 'EDAPADI': 'SALEM',
 'EGMORE': 'CHENNAI',
 'ERODE (East)': 'ERODE',
 'ERODE (West)': 'ERODE',
 'GANDHARVAKOTTAI': 'PUDUKKOTTAI',
 'GANGAVALLI': 'SALEM',
 'GINGEE': 'VILLUPURAM',
 'GOBICHETTIPALAYAM': 'TIRUPUR',
 'GUDALUR': 'TIRUPUR',
 'GUDIYATHAM': 'VELLORE',
 'GUMMIDIPUNDI': 'TIRUVALLUR',
 'HARBOUR': 'CHENNAI',
 'HARUR': 'DHARMAPURI',
 'HOSUR': 'KRISHNAGIRI',
 'JAYANKONDAM': 'ARIYALUR',
 'JOLARPET': 'VELLORE',
 'KADAYANALLUR': 'TIRUNELVELI',
 'KALASAPAKKAM': 'TIRUVANNAMALAI',
 'KALLAKURICHI': 'VILLUPURAM',
 'KANCHEEPURAM': 'KANCHIPURAM',
 'KANGAYAM': 'ERODE',
 'KANNIYAKUMARI': 'KANNIYAKUMARI',
 'KARAIKUDI': 'SIVAGANGA',
 'KARUR': 'KARUR',
 'KATPADI': 'VELLORE',
 'KATTUMANNARKOIL': 'CUDDALORE',
 'KAVUNDAMPALAYAM': 'COIMBATORE',
 'KILLIYOOR': 'KANNIYAKUMARI',
 'KILPENNATHUR': 'TIRUVANNAMALAI',
 'KILVAITHINANKUPPAM': 'VELLORE',
 'KILVELUR': 'NAGAPATTINAM',
 'KINATHUKADAVU': 'COIMBATORE',
 'KOLATHUR': 'CHENNAI',
 'KOVILPATTI': 'THOOTHUKUDI',
 'KRISHNAGIRI': 'KRISHNAGIRI',
 'KRISHNARAYAPURAM': 'KARUR',
 'KULITHALAI': 'KARUR',
 'KUMARAPALAYAM': 'NAMAKKAL',
 'KUMBAKONAM': 'THANJAVUR',
 'KUNNAM': 'PERAMBALUR',
 'KURINJIPADI': 'CUDDALORE',
 'LALGUDI': 'TIRUCHIRAPPALLI',
 'MADATHUKULAM': 'COIMBATORE',
 'MADAVARAM': 'TIRUVALLUR',
 'MADURAI CENTRAL': 'MADURAI',
 'MADURAI EAST': 'MADURAI',
 'MADURAI NORTH': 'MADURAI',
 'MADURAI SOUTH': 'MADURAI',
 'MADURAI WEST': 'MADURAI',
 'MADURANTHAKAM': 'KANCHIPURAM',
 'MADURAVOYAL': 'TIRUVALLUR',
 'MAILAM': 'VILLUPURAM',
 'MANACHANALLUR': 'TIRUCHIRAPPALLI',
 'MANAMADURAI': 'SIVAGANGA',
 'MANAPPARAI': 'TIRUCHIRAPPALLI',
 'MANNARGUDI': 'TIRUVARUR',
 'MAYILADUTHURAI': 'NAGAPATTINAM',
 'MELUR': 'MADURAI',
 'METTUPALAYAM': 'TIRUPUR',
 'METTUR': 'SALEM',
 'MODAKURICHI': 'ERODE',
 'MUDUKULATHUR': 'RAMANATHAPURAM',
 'MUSIRI': 'TIRUCHIRAPPALLI',
 'MYLAPORE': 'CHENNAI',
 'NAGAPATTINAM': 'NAGAPATTINAM',
 'NAGERCOIL': 'KANNIYAKUMARI',
 'NAMAKKAL': 'NAMAKKAL',
 'NANGUNERI': 'TIRUNELVELI',
 'NANNILAM': 'TIRUVARUR',
 'NATHAM': 'DINDIGUL',
 'NEYVELI': 'CUDDALORE',
 'NILAKOTTAI': 'DINDIGUL',
 'ODDANCHATRAM': 'DINDIGUL',
 'OMALUR': 'SALEM',
 'ORATHANAD': 'THANJAVUR',
 'OTTAPIDARAM': 'THOOTHUKUDI',
 'PADMANABHAPURAM': 'KANNIYAKUMARI',
 'PALACODE': 'DHARMAPURI',
 'PALANI': 'DINDIGUL',
 'PALAYAMCOTTAI': 'TIRUNELVELI',
 'PALLADAM': 'NILGIRIS',
 'PALLAVARAM': 'KANCHIPURAM',
 'PANRUTI': 'CUDDALORE',
 'PAPANASAM': 'THANJAVUR',
 'PAPPIREDDIPPATTI': 'DHARMAPURI',
 'PARAMAKUDI': 'RAMANATHAPURAM',
 'PARAMATHI-VELUR': 'NAMAKKAL',
 'PATTUKKOTTAI': 'THANJAVUR',
 'PENNAGARAM': 'DHARMAPURI',
 'PERAMBALUR': 'PERAMBALUR',
 'PERAMBUR': 'CHENNAI',
 'PERAVURANI': 'THANJAVUR',
 'PERIYAKULAM': 'THENI',
 'PERUNDURAI': 'ERODE',
 'POLLACHI': 'COIMBATORE',
 'POLUR': 'TIRUVANNAMALAI',
 'PONNERI': 'TIRUVALLUR',
 'POOMPUHAR': 'NAGAPATTINAM',
 'POONAMALLEE': 'TIRUVALLUR',
 'PUDUKKOTTAI': 'PUDUKKOTTAI',
 'RADHAPURAM': 'TIRUNELVELI',
 'RAJAPALAYAM': 'VIRUDHUNAGAR',
 'RAMANATHAPURAM': 'RAMANATHAPURAM',
 'RANIPET': 'VELLORE',
 'RASIPURAM': 'NAMAKKAL',
 'RISHIVANDIAM': 'VILLUPURAM',
 'ROYAPURAM': 'CHENNAI',
 'SAIDAPET': 'CHENNAI',
 'SALEM (North)': 'SALEM',
 'SALEM (South)': 'SALEM',
 'SALEM (West)': 'SALEM',
 'SANKARANKOVIL': 'TIRUNELVELI',
 'SANKARAPURAM': 'VILLUPURAM',
 'SANKARI': 'SALEM',
 'SATTUR': 'VIRUDHUNAGAR',
 'SENDAMANGALAM': 'NAMAKKAL',
 'SHOLAVANDAN': 'MADURAI',
 'SHOLINGHUR': 'VELLORE',
 'SHOZHINGANALLUR': 'KANCHIPURAM',
 'SINGANALLUR': 'COIMBATORE',
 'SIRKALI': 'NAGAPATTINAM',
 'SIVAGANGA': 'SIVAGANGA',
 'SIVAKASI': 'VIRUDHUNAGAR',
 'SRIPERUMBUDUR': 'KANCHIPURAM',
 'SRIRANGAM': 'TIRUCHIRAPPALLI',
 'SRIVAIKUNTAM': 'THOOTHUKUDI',
 'SRIVILLIPUTHUR': 'VIRUDHUNAGAR',
 'SULUR': 'NILGIRIS',
 'TAMBARAM': 'KANCHIPURAM',
 'TENKASI': 'TIRUNELVELI',
 'THALLI': 'KRISHNAGIRI',
 'THANJAVUR': 'THANJAVUR',
 'THEAYAGARAYA NAGAR': 'CHENNAI',
 'THIRU-VI-KA-NAGAR': 'CHENNAI',
 'THIRUMANGALAM': 'MADURAI',
 'THIRUMAYAM': 'PUDUKKOTTAI',
 'THIRUPARANKUNDRAM': 'MADURAI',
 'THIRUPORUR': 'KANCHIPURAM',
 'THIRUTHURAIPUNDI': 'TIRUVARUR',
 'THIRUVAIYARU': 'THANJAVUR',
 'THIRUVALLUR': 'TIRUVALLUR',
 'THIRUVARUR': 'TIRUVARUR',
 'THIRUVERAMBUR': 'TIRUCHIRAPPALLI',
 'THIRUVIDAMARUDUR': 'THANJAVUR',
 'THIRUVOTTIYUR': 'TIRUVALLUR',
 'THONDAMUTHUR': 'COIMBATORE',
 'THOOTHUKKUDI': 'THOOTHUKUDI',
 'THOUSAND LIGHTS': 'CHENNAI',
 'THURAIYUR': 'TIRUCHIRAPPALLI',
 'TINDIVANAM': 'VILLUPURAM',
 'TIRUCHENDUR': 'THOOTHUKUDI',
 'TIRUCHENGODE': 'NAMAKKAL',
 'TIRUCHIRAPALLI (East)': 'TIRUCHIRAPPALLI',
 'TIRUCHIRAPALLI (West)': 'TIRUCHIRAPPALLI',
 'TIRUCHULI': 'VIRUDHUNAGAR',
 'TIRUKKOYILUR': 'VILLUPURAM',
 'TIRUNELVELI': 'TIRUNELVELI',
 'TIRUPPATTUR': 'VELLORE',
 'TIRUPPUR (North)': 'TIRUPUR',
 'TIRUPPUR (South)': 'NILGIRIS',
 'TIRUTTANI': 'TIRUVALLUR',
 'TIRUVADANAI': 'RAMANATHAPURAM',
 'TIRUVANNAMALAI': 'TIRUVANNAMALAI',
 'TITTAKUDI': 'CUDDALORE',
 'UDHAGAMANDALAM': 'TIRUPUR',
 'UDUMALPET': 'COIMBATORE',
 'ULUNDURPET': 'VILLUPURAM',
 'USILAMPATTI': 'MADURAI',
 'UTHANGARAI': 'KRISHNAGIRI',
 'UTHIRAMERUR': 'KANCHIPURAM',
 'VALPARAI': 'COIMBATORE',
 'VANDAVASI': 'TIRUVANNAMALAI',
 'VANIAYAMBADI': 'VELLORE',
 'VANUR': 'VILLUPURAM',
 'VASUDEVANALLUR': 'TIRUNELVELI',
 'VEDARANYAM': 'NAGAPATTINAM',
 'VEDASANDUR': 'DINDIGUL',
 'VEERAPANDI': 'SALEM',
 'VELACHERY': 'CHENNAI',
 'VELLORE': 'VELLORE',
 'VEPPANAHALLI': 'KRISHNAGIRI',
 'VIKRAVANDI': 'VILLUPURAM',
 'VILATHIKULAM': 'THOOTHUKUDI',
 'VILAVANCODE': 'KANNIYAKUMARI',
 'VILLIVAKKAM': 'CHENNAI',
 'VILLUPURAM': 'VILLUPURAM',
 'VIRALIMALAI': 'PUDUKKOTTAI',
 'VIRUDHUNAGAR': 'VIRUDHUNAGAR',
 'VIRUGAMPAKKAM': 'CHENNAI',
 'VRIDDHACHALAM': 'CUDDALORE',
 'YERCAUD': 'SALEM',
 'PARK TOWN': 'CHENNAI',
 'PURASAWALKAM': 'CHENNAI'}

In [370]:
import numpy as np
dii={}
for k1,k2 in zip(dd['Constituency_Name'],dd['District_Name']):
    if pd.isnull(k2):
        k2=di.get(k1)
    dii.update({k1:k2})

In [371]:
dii

{'GUMMIDIPUNDI': 'TIRUVALLUR',
 'PONNERI': 'TIRUVALLUR',
 'TIRUTTANI': 'TIRUVALLUR',
 'THIRUVALLUR': 'TIRUVALLUR',
 'POONAMALLEE': 'TIRUVALLUR',
 'AVADI': 'TIRUVALLUR',
 'MADURAVOYAL': 'TIRUVALLUR',
 'AMBATTUR': 'TIRUVALLUR',
 'MADAVARAM': 'TIRUVALLUR',
 'THIRUVOTTIYUR': 'TIRUVALLUR',
 'DR. RADHAKRISHNAN NAGAR': 'CHENNAI',
 'PERAMBUR': 'CHENNAI',
 'KOLATHUR': 'CHENNAI',
 'VILLIVAKKAM': 'CHENNAI',
 'THIRU-VI-KA-NAGAR': 'CHENNAI',
 'EGMORE': 'CHENNAI',
 'ROYAPURAM': 'CHENNAI',
 'HARBOUR': 'CHENNAI',
 'CHEPAUK-THIRUVALLIKENI': 'CHENNAI',
 'THOUSAND LIGHTS': 'CHENNAI',
 'ANNA NAGAR': 'CHENNAI',
 'VIRUGAMPAKKAM': 'CHENNAI',
 'SAIDAPET': 'CHENNAI',
 'THEAYAGARAYA NAGAR': 'CHENNAI',
 'MYLAPORE': 'CHENNAI',
 'VELACHERY': 'CHENNAI',
 'SHOZHINGANALLUR': 'KANCHIPURAM',
 'ALANDUR': 'KANCHIPURAM',
 'SRIPERUMBUDUR': 'KANCHIPURAM',
 'PALLAVARAM': 'KANCHIPURAM',
 'TAMBARAM': 'KANCHIPURAM',
 'CHENGALPATTU': 'KANCHIPURAM',
 'THIRUPORUR': 'KANCHIPURAM',
 'CHEYYUR': 'KANCHIPURAM',
 'MADURANTHAKAM': 'KANCHIPURAM',
 'UTHIRAMERUR': 'KANCHIPURAM',
 'KANCHEEPURAM': 'KANCHIPURAM',
 'ARAKONAM': 'VELLORE',
 'SHOLINGHUR': 'VELLORE',
 'KATPADI': 'VELLORE',
 'RANIPET': 'VELLORE',
 'ARCOT': 'VELLORE',
 'VELLORE': 'VELLORE',
 'ANAIKATTU': 'VELLORE',
 'KILVAITHINANKUPPAM': 'VELLORE',
 'GUDIYATHAM': 'VELLORE',
 'VANIAYAMBADI': 'VELLORE',
 'AMBUR': 'VELLORE',
 'JOLARPET': 'VELLORE',
 'TIRUPPATTUR': 'VELLORE',
 'UTHANGARAI': 'KRISHNAGIRI',
 'BARGUR': 'KRISHNAGIRI',
 'KRISHNAGIRI': 'KRISHNAGIRI',
 'VEPPANAHALLI': 'KRISHNAGIRI',
 'HOSUR': 'KRISHNAGIRI',
 'THALLI': 'KRISHNAGIRI',
 'PALACODE': 'DHARMAPURI',
 'PENNAGARAM': 'DHARMAPURI',
 'DHARMAPURI': 'DHARMAPURI',
 'PAPPIREDDIPPATTI': 'DHARMAPURI',
 'HARUR': 'DHARMAPURI',
 'CHENGAM': 'TIRUVANNAMALAI',
 'TIRUVANNAMALAI': 'TIRUVANNAMALAI',
 'KILPENNATHUR': 'TIRUVANNAMALAI',
 'KALASAPAKKAM': 'TIRUVANNAMALAI',
 'POLUR': 'TIRUVANNAMALAI',
 'ARANI': 'TIRUVANNAMALAI',
 'CHEYYAR': 'TIRUVANNAMALAI',
 'VANDAVASI': 'TIRUVANNAMALAI',
 'GINGEE': 'VILLUPURAM',
 'MAILAM': 'VILLUPURAM',
 'TINDIVANAM': 'VILLUPURAM',
 'VANUR': 'VILLUPURAM',
 'VILLUPURAM': 'VILLUPURAM',
 'VIKRAVANDI': 'VILLUPURAM',
 'TIRUKKOYILUR': 'VILLUPURAM',
 'ULUNDURPET': 'VILLUPURAM',
 'RISHIVANDIAM': 'VILLUPURAM',
 'SANKARAPURAM': 'VILLUPURAM',
 'KALLAKURICHI': 'VILLUPURAM',
 'GANGAVALLI': 'SALEM',
 'ATTUR': 'SALEM',
 'YERCAUD': 'SALEM',
 'OMALUR': 'SALEM',
 'METTUR': 'SALEM',
 'EDAPADI': 'SALEM',
 'SANKARI': 'SALEM',
 'SALEM (West)': 'SALEM',
 'SALEM (North)': 'SALEM',
 'SALEM (South)': 'SALEM',
 'VEERAPANDI': 'SALEM',
 'RASIPURAM': 'NAMAKKAL',
 'SENDAMANGALAM': 'NAMAKKAL',
 'NAMAKKAL': 'NAMAKKAL',
 'PARAMATHI-VELUR': 'NAMAKKAL',
 'TIRUCHENGODE': 'NAMAKKAL',
 'KUMARAPALAYAM': 'NAMAKKAL',
 'ERODE (East)': 'ERODE',
 'ERODE (West)': 'ERODE',
 'MODAKURICHI': 'ERODE',
 'DHARAPURAM': 'ERODE',
 'KANGAYAM': 'ERODE',
 'PERUNDURAI': 'ERODE',
 'BHAVANI': 'ERODE',
 'ANTHIYUR': 'ERODE',
 'GOBICHETTIPALAYAM': 'TIRUPUR',
 'BHAVANISAGAR': 'TIRUPUR',
 'UDHAGAMANDALAM': 'TIRUPUR',
 'GUDALUR': 'TIRUPUR',
 'COONOOR': 'TIRUPUR',
 'METTUPALAYAM': 'TIRUPUR',
 'AVANASHI': 'TIRUPUR',
 'TIRUPPUR (North)': 'TIRUPUR',
 'TIRUPPUR (South)': 'NILGIRIS',
 'PALLADAM': 'NILGIRIS',
 'SULUR': 'NILGIRIS',
 'KAVUNDAMPALAYAM': 'COIMBATORE',
 'COIMBATORE NORTH': 'COIMBATORE',
 'THONDAMUTHUR': 'COIMBATORE',
 'COIMBATORE SOUTH': 'COIMBATORE',
 'SINGANALLUR': 'COIMBATORE',
 'KINATHUKADAVU': 'COIMBATORE',
 'POLLACHI': 'COIMBATORE',
 'VALPARAI': 'COIMBATORE',
 'UDUMALPET': 'COIMBATORE',
 'MADATHUKULAM': 'COIMBATORE',
 'PALANI': 'DINDIGUL',
 'ODDANCHATRAM': 'DINDIGUL',
 'ATHOOR': 'DINDIGUL',
 'NILAKOTTAI': 'DINDIGUL',
 'NATHAM': 'DINDIGUL',
 'DINDIGUL': 'DINDIGUL',
 'VEDASANDUR': 'DINDIGUL',
 'ARAVAKURICHI': 'KARUR',
 'KARUR': 'KARUR',
 'KRISHNARAYAPURAM': 'KARUR',
 'KULITHALAI': 'KARUR',
 'MANAPPARAI': 'TIRUCHIRAPPALLI',
 'SRIRANGAM': 'TIRUCHIRAPPALLI',
 'TIRUCHIRAPALLI (West)': 'TIRUCHIRAPPALLI',
 'TIRUCHIRAPALLI (East)': 'TIRUCHIRAPPALLI',
 'THIRUVERAMBUR': 'TIRUCHIRAPPALLI',
 'LALGUDI': 'TIRUCHIRAPPALLI',
 'MANACHANALLUR': 'TIRUCHIRAPPALLI',
 'MUSIRI': 'TIRUCHIRAPPALLI',
 'THURAIYUR': 'TIRUCHIRAPPALLI',
 'PERAMBALUR': 'PERAMBALUR',
 'KUNNAM': 'PERAMBALUR',
 'ARIYALUR': 'ARIYALUR',
 'JAYANKONDAM': 'ARIYALUR',
 'TITTAKUDI': 'CUDDALORE',
 'VRIDDHACHALAM': 'CUDDALORE',
 'NEYVELI': 'CUDDALORE',
 'PANRUTI': 'CUDDALORE',
 'CUDDALORE': 'CUDDALORE',
 'KURINJIPADI': 'CUDDALORE',
 'BHUVANAGIRI': 'CUDDALORE',
 'CHIDAMBARAM': 'CUDDALORE',
 'KATTUMANNARKOIL': 'CUDDALORE',
 'SIRKALI': 'NAGAPATTINAM',
 'MAYILADUTHURAI': 'NAGAPATTINAM',
 'POOMPUHAR': 'NAGAPATTINAM',
 'NAGAPATTINAM': 'NAGAPATTINAM',
 'KILVELUR': 'NAGAPATTINAM',
 'VEDARANYAM': 'NAGAPATTINAM',
 'THIRUTHURAIPUNDI': 'TIRUVARUR',
 'MANNARGUDI': 'TIRUVARUR',
 'THIRUVARUR': 'TIRUVARUR',
 'NANNILAM': 'TIRUVARUR',
 'THIRUVIDAMARUDUR': 'THANJAVUR',
 'KUMBAKONAM': 'THANJAVUR',
 'PAPANASAM': 'THANJAVUR',
 'THIRUVAIYARU': 'THANJAVUR',
 'THANJAVUR': 'THANJAVUR',
 'ORATHANAD': 'THANJAVUR',
 'PATTUKKOTTAI': 'THANJAVUR',
 'PERAVURANI': 'THANJAVUR',
 'GANDHARVAKOTTAI': 'PUDUKKOTTAI',
 'VIRALIMALAI': 'PUDUKKOTTAI',
 'PUDUKKOTTAI': 'PUDUKKOTTAI',
 'THIRUMAYAM': 'PUDUKKOTTAI',
 'ALANGUDI': 'PUDUKKOTTAI',
 'ARANTANGI': 'PUDUKKOTTAI',
 'KARAIKUDI': 'SIVAGANGA',
 'SIVAGANGA': 'SIVAGANGA',
 'MANAMADURAI': 'SIVAGANGA',
 'MELUR': 'MADURAI',
 'MADURAI EAST': 'MADURAI',
 'SHOLAVANDAN': 'MADURAI',
 'MADURAI NORTH': 'MADURAI',
 'MADURAI SOUTH': 'MADURAI',
 'MADURAI CENTRAL': 'MADURAI',
 'MADURAI WEST': 'MADURAI',
 'THIRUPARANKUNDRAM': 'MADURAI',
 'THIRUMANGALAM': 'MADURAI',
 'USILAMPATTI': 'MADURAI',
 'ANDIPATTI': 'THENI',
 'PERIYAKULAM': 'THENI',
 'BODINAYAKANUR': 'THENI',
 'CUMBUM': 'THENI',
 'RAJAPALAYAM': 'VIRUDHUNAGAR',
 'SRIVILLIPUTHUR': 'VIRUDHUNAGAR',
 'SATTUR': 'VIRUDHUNAGAR',
 'SIVAKASI': 'VIRUDHUNAGAR',
 'VIRUDHUNAGAR': 'VIRUDHUNAGAR',
 'ARUPPUKOTTAI': 'VIRUDHUNAGAR',
 'TIRUCHULI': 'VIRUDHUNAGAR',
 'PARAMAKUDI': 'RAMANATHAPURAM',
 'TIRUVADANAI': 'RAMANATHAPURAM',
 'RAMANATHAPURAM': 'RAMANATHAPURAM',
 'MUDUKULATHUR': 'RAMANATHAPURAM',
 'VILATHIKULAM': 'THOOTHUKUDI',
 'THOOTHUKKUDI': 'THOOTHUKUDI',
 'TIRUCHENDUR': 'THOOTHUKUDI',
 'SRIVAIKUNTAM': 'THOOTHUKUDI',
 'OTTAPIDARAM': 'THOOTHUKUDI',
 'KOVILPATTI': 'THOOTHUKUDI',
 'SANKARANKOVIL': 'TIRUNELVELI',
 'VASUDEVANALLUR': 'TIRUNELVELI',
 'KADAYANALLUR': 'TIRUNELVELI',
 'TENKASI': 'TIRUNELVELI',
 'ALANGULAM': 'TIRUNELVELI',
 'TIRUNELVELI': 'TIRUNELVELI',
 'AMBASAMUDRAM': 'TIRUNELVELI',
 'PALAYAMCOTTAI': 'TIRUNELVELI',
 'NANGUNERI': 'TIRUNELVELI',
 'RADHAPURAM': 'TIRUNELVELI',
 'KANNIYAKUMARI': 'KANNIYAKUMARI',
 'NAGERCOIL': 'KANNIYAKUMARI',
 'COLACHEL': 'KANNIYAKUMARI',
 'PADMANABHAPURAM': 'KANNIYAKUMARI',
 'VILAVANCODE': 'KANNIYAKUMARI',
 'KILLIYOOR': 'KANNIYAKUMARI',
 'PARK TOWN': 'CHENNAI',
 'PURASAWALKAM': 'CHENNAI',
 'THEAGARAYA NAGAR': None,
 'CHEPAUK': None,
 'TRIPLICANE': None,
 'TIRUPPORUR': None,
 'ACHARAPAKKAM': None,
 'TIRUVALLUR': None,
 'PALLIPET': None,
 'ARKONAM': None,
 'PERNAMBUT': None,
 'NATRAMPALLI': None,
 'THANDARAMBATTU': None,
 'ANAICUT': None,
 'ARNI': None,
 'PERANAMALLUR': None,
 'MELMALAYANUR': None,
 'KANDAMANGALAM': None,
 'MUGAIYUR': None,
 'THIRUNAVALUR': None,
 'NELLIKUPPAM': None,
 'VRIDHACHALAM': None,
 'MANGALORE': None,
 'CHINNASALEM': None,
 'KAVERIPATTINAM': None,
 'MORAPPUR': None,
 'TARAMANGALAM': None,
 'SALEM-I': None,
 'SALEM-II': None,
 'PANAMARATHUPATTY': None,
 'TALAVASAL': None,
 'KAPILAMALAI': None,
 'COIMBATORE WEST': None,
 'COIMBATORE EAST': None,
 'PERUR': None,
 'KINATHUKKADAVU': None,
 'VELLAKOIL': None,
 'PONGALUR': None,
 'TIRUPPUR': None,
 'ERODE': None,
 'ANDHIYUR': None,
 'SATHYAMANGALAM': None,
 'OOTACAMUND': None,
 'THENI': None,
 'BODINAYAKKANUR': None,
 'SEDAPATTI': None,
 'TIRUPPARANKUNDRAM': None,
 'MADURAICENTRAL': None,
 'SAMAYANALLUR': None,
 'MARUNGAPURI': None,
 'THOTTIAM': None,
 'UPPILIAPURAM': None,
 'VARAHUR': None,
 'ANDIMADAM': None,
 'TIRUCHIRAPALLI-I': None,
 'TIRUCHIRAPALLI-II': None,
 'MAYURAM': None,
 'KUTTALAM': None,
 'TIRUVARUR': None,
 'TIRUTHURAIPUNDI': None,
 'THIRUVONAM': None,
 'TIRUVAIYARU': None,
 'VALANGIMAN': None,
 'ILAYANGUDI': None,
 'KADALADI': None,
 'POTTAPIDARAM': None,
 'KOILPATTI': None,
 'SANKARANAYANARKOIL': None,
 'CHERANMAHADEVI': None,
 'SATTANGULAM': None,
 'TUTICORIN': None,
 'THIRUVATTAR': None,
 'MADURAIWEST': None,
 'VANDAVASI (SC)': None,
 'THONOAMUTHUR': None,
 'THIRUMANGLAM': None,
 'ACHARAPAKAM': None,
 'VINIYAMBADI': None,
 'SATTANKULAM': None,
 'PUDUKOTTAI': None,
 'NELLIKPPAM': None,
 'TIRUCHIRAPALLIII': None,
 'ARUNTANGI': None,
 'ANNA': None,
 'ARAKKONAM': None,
 'VANDAVASHI': None,
 'DHARAMAPURI': None,
 'UPPILIAPURAM(ST)': None,
 'TIRUCHIRAPPALLI-I': None,
 'TIRUCHIRAPPALLI-II': None,
 'THIRUMAIYAM': None,
 'HADHA': None,
 'THIRUCHIRAPPALLI-I': None,
 'THIRUCHIRAPPALLI-II': None,
 'WASHERMANPET': None,
 'BASIN BRIDGE': None,
 'THIAGARAYANAGAR': None,
 'TIRUVOTRIYUR': None,
 'ST THOMAS MOUNT': None,
 'CHINGLEPUT': None,
 'MADURANTAKAM': None,
 'UTTIRAMERUR': None,
 'KUNNATHUR': None,
 'KADAMBATHUR': None,
 'SHOKINGHUR': None,
 'GUDIYATTAM': None,
 'PERNAMBATTU': None,
 'TIRUPATTUR': None,
 'VANIYAMBADI': None,
 'KANIYAMBADI': None,
 'WANDIWASH': None,
 'PERNAMALLUR': None,
 'THANDRAMBA': None,
 'KALASPAKKAM': None,
 'KANDAMAGALAM': None,
 'MANGALUR': None,
 'TIRUKKOILUR': None,
 'RISHIVADIYAM': None,
 'UDDANAPALLE': None,
 'KAVERIPATNAM': None,
 'UTTANGARAI': None,
 'SALEM I': None,
 'SALEM I I': None,
 'PANAMRATHUPATTI': None,
 'VEERAPANDY': None,
 'EDAPPADI': None,
 'MODAKKURICHI': None,
 'PERUNIURAI': None,
 'SATYAMANGALAM': None,
 'ODDAMCHATRAM': None,
 'PERIAKULAM': None,
 'NILAKKOTTAI': None,
 'THIRUPPARANKUNDRAM': None,
 'MELUR SOUTH': None,
 'MELUR NORTH': None,
 'VADAMADURAI': None,
 'THOTTIYAM': None,
 'UPPILIYAPURAM': None,
 'ARIYAIUR': None,
 'TIRUCHIRAPPALLI I': None,
 'I': None,
 'THIRUVARAMBUR': None,
 'KULITTALAI': None,
 'KADAVUR': None,
 'ALANGUDY': None,
 'ADUTHURAI': None,
 'SEMBANARKOIL': None,
 'KODAVASAL': None,
 'KOTTUR': None,
 'GANDARVAKOTTAI': None,
 'PERAURANI': None,
 'ARANTHANGI': None,
 'KARIAPATTI': None,
 'ARUPPUKKOTTAI': None,
 'SANKARANKOIL': None,
 'GANGAIKONDAN': None,
 'MELAPALAYAM': None,
 'KANYAKUMARI': None,
 'TIRUVATTAR': None}

In [373]:
ll=[0,1,2,3,4,5]
for i in ll:
    if (i+1) % 3==0:
        print()
    print(i)

0
1

2
3
4

5

In [451]:
from sklearn.ensemble import RandomForestRegressor#for sklearn.ensemble installation-->pip install scikit-learn
# Assuming dd is your DataFrame
daata = dd.groupby(['Year', 'Constituency_Name']).agg({'Valid_Votes': set, 'Turnout_Percentage': set,'Electors':set}).reset_index()

# Convert sets to lists
daata['Valid_Votes'] = daata['Valid_Votes'].apply(list)
daata['Turnout_Percentage'] = daata['Turnout_Percentage'].apply(list)
daata['Electors'] = daata['Electors'].apply(list)
daata['Valid_Votes'] = daata['Valid_Votes'].str[0]
daata['Turnout_Percentage'] = daata['Turnout_Percentage'].str[0]
daata['Electors'] = daata['Electors'].str[0]

In [452]:
daata

      Year Constituency_Name  Valid_Votes  Turnout_Percentage  Electors
0     1971      ACHARAPAKKAM        59636               70.09     85083
1     1971         ADUTHURAI        78083               79.93     97689
2     1971          ALANGUDY        79826               83.96     95080
3     1971         ALANGULAM        71214               76.19     93471
4     1971      AMBASAMUDRAM        67047               70.74     94781
...    ...               ...          ...                 ...       ...
2855  2021       VIRALIMALAI       193423               85.43    226411
2856  2021      VIRUDHUNAGAR       161717               71.27    226907
2857  2021     VIRUGAMPAKKAM       169087               57.59    293604
2858  2021     VRIDDHACHALAM       196734               77.02    255432
2859  2021           YERCAUD       238924               83.09    287548

[2860 rows x 5 columns]

In [453]:
df_encoded=pd.get_dummies(daata,'Constituency_Name')

In [454]:
df_encoded

,Year,Valid_Votes,Turnout_Percentage,Electors,Constituency_Name_ACHARAPAKAM,Constituency_Name_ACHARAPAKKAM,Constituency_Name_ADUTHURAI,Constituency_Name_ALANDUR,Constituency_Name_ALANGUDI,Constituency_Name_ALANGUDY,...,Constituency_Name_VILLUPURAM,Constituency_Name_VINIYAMBADI,Constituency_Name_VIRALIMALAI,Constituency_Name_VIRUDHUNAGAR,Constituency_Name_VIRUGAMPAKKAM,Constituency_Name_VRIDDHACHALAM,Constituency_Name_VRIDHACHALAM,Constituency_Name_WANDIWASH,Constituency_Name_WASHERMANPET,Constituency_Name_YERCAUD
0,1971,59636,70.09,85083,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1971,78083,79.93,97689,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1971,79826,83.96,95080,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1971,71214,76.19,93471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1971,67047,70.74,94781,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2855,2021,193423,85.43,226411,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2856,2021,161717,71.27,226907,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2857,2021,169087,57.59,293604,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2858,2021,196734,77.02,255432,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2859,2021,238924,83.09,287548,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [457]:
X = df_encoded.drop(columns=['Valid_Votes','Turnout_Percentage','Electors'])
y = df_encoded[['Valid_Votes','Turnout_Percentage','Electors']]

In [458]:
X

,Year,Constituency_Name_ACHARAPAKAM,Constituency_Name_ACHARAPAKKAM,Constituency_Name_ADUTHURAI,Constituency_Name_ALANDUR,Constituency_Name_ALANGUDI,Constituency_Name_ALANGUDY,Constituency_Name_ALANGULAM,Constituency_Name_AMBASAMUDRAM,Constituency_Name_AMBATTUR,...,Constituency_Name_VILLUPURAM,Constituency_Name_VINIYAMBADI,Constituency_Name_VIRALIMALAI,Constituency_Name_VIRUDHUNAGAR,Constituency_Name_VIRUGAMPAKKAM,Constituency_Name_VRIDDHACHALAM,Constituency_Name_VRIDHACHALAM,Constituency_Name_WANDIWASH,Constituency_Name_WASHERMANPET,Constituency_Name_YERCAUD
0,1971,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1971,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1971,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1971,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1971,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2855,2021,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2856,2021,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2857,2021,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2858,2021,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2859,2021,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [459]:
y

      Valid_Votes  Turnout_Percentage  Electors
0           59636               70.09     85083
1           78083               79.93     97689
2           79826               83.96     95080
3           71214               76.19     93471
4           67047               70.74     94781
...           ...                 ...       ...
2855       193423               85.43    226411
2856       161717               71.27    226907
2857       169087               57.59    293604
2858       196734               77.02    255432
2859       238924               83.09    287548

[2860 rows x 3 columns]

In [460]:
rfr=RandomForestRegressor(n_estimators=10,random_state=4)
rfr.fit(X,y)

RandomForestRegressor(n_estimators=10, random_state=4)

In [461]:
cc=daata['Constituency_Name'].unique()
cc1=pd.get_dummies(cc)
cc1

,ACHARAPAKAM,ACHARAPAKKAM,ADUTHURAI,ALANDUR,ALANGUDI,ALANGUDY,ALANGULAM,AMBASAMUDRAM,AMBATTUR,AMBUR,...,VILLUPURAM,VINIYAMBADI,VIRALIMALAI,VIRUDHUNAGAR,VIRUGAMPAKKAM,VRIDDHACHALAM,VRIDHACHALAM,WANDIWASH,WASHERMANPET,YERCAUD
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
388,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
389,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
391,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [498]:
kk=cc1['TIRUCHENDUR'].tolist()
kk.insert(0,2016)

In [499]:
kk=np.array([kk]).reshape(1,-1)
kk

array([[2016,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]])

In [500]:
kl=rfr.predict(kk)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [501]:
kl
'''
The output you are seeing, array([[1.737776e+05, 7.518500e+01, 2.314672e+05]]), is a representation of a NumPy array with scientific notation for the values.

Here's the breakdown of the values in the array:

The first value is 1.737776e+05, which is equivalent to 173,777.6 in standard decimal notation.
The second value is 7.518500e+01, which is equivalent to 75.185 in standard decimal notation.
The third value is 2.314672e+05, which is equivalent to 231,467.2 in standard decimal notation.
The e+05 in scientific notation means "times 10 to the power of 5."
'''

'\nThe output you are seeing, array([[1.737776e+05, 7.518500e+01, 2.314672e+05]]), is a representation of a NumPy array with scientific notation for the values.\n\nHere\'s the breakdown of the values in the array:\n\nThe first value is 1.737776e+05, which is equivalent to 173,777.6 in standard decimal notation.\nThe second value is 7.518500e+01, which is equivalent to 75.185 in standard decimal notation.\nThe third value is 2.314672e+05, which is equivalent to 231,467.2 in standard decimal notation.\nThe e+05 in scientific notation means "times 10 to the power of 5."\n'

In [502]:
value1, value2, value3 =kl[0]


# Displaying the formatted values
print(value1,value2,value3)

173777.6 75.185 231467.2

In [503]:
rfr.score(X,y)

0.9419900136268042

In [493]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.001,random_state=2)

In [494]:
lo=LinearRegression()
lo.fit(x_train,y_train)

LinearRegression()

In [504]:
l=lo.predict(kk)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [505]:
v1,v2,v3=l[0]
print(v1,v2,v3)

148029.538535038 65.77001410004732 216554.2277503768

In [497]:
lo.score(X,y)

0.7236747079852696

In [3]:
import pandas as pd

# Assuming k_x is your DataFrame
k_x = pd.DataFrame({'Constituency_Name': ['A', 'B', 'A', 'C', 'B']})

# Create dummy variables
en_code = pd.get_dummies(k_x['Constituency_Name'])

# Display the result
print(en_code.transpose())

   0  1  2  3  4
A  1  0  1  0  0
B  0  1  0  0  1
C  0  0  0  1  0

In [6]:
x=dd.groupby(['Year','Constituency_Name','Party'])['Votes'].unique().reset_index()
x['Votes']=x['Votes'].str[0]

In [7]:
X=pd.get_dummies(x,columns=['Constituency_Name','Party'])
X

,Year,Votes,Constituency_Name_ACHARAPAKAM,Constituency_Name_ACHARAPAKKAM,Constituency_Name_ADUTHURAI,Constituency_Name_ALANDUR,Constituency_Name_ALANGUDI,Constituency_Name_ALANGUDY,Constituency_Name_ALANGULAM,Constituency_Name_AMBASAMUDRAM,...,Party_VBMP,Party_VCK,Party_VTIP,Party_VTK,Party_VVIP,Party_Valamaana Tamizhagam Katchi,Party_Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi,Party_Vidial Valarchi Perani,Party_WPOI,Party_YSP
0,1971,39816,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1971,4346,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1971,13457,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1971,40023,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1971,38060,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16606,2021,95606,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16607,2021,876,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16608,2021,660,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16609,2021,1979,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16610,2021,13308,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
from sklearn.ensemble import RandomForestRegressor
xx=X.drop('Votes',axis=1).values
yy=X['Votes'].values
rfr2=RandomForestRegressor(n_estimators=5,random_state=90)
rfr2.fit(xx,yy)

RandomForestRegressor(n_estimators=5, random_state=90)

In [11]:
en_code=pd.get_dummies(x[['Constituency_Name','Party']])

In [12]:
en_code

,Constituency_Name_ACHARAPAKAM,Constituency_Name_ACHARAPAKKAM,Constituency_Name_ADUTHURAI,Constituency_Name_ALANDUR,Constituency_Name_ALANGUDI,Constituency_Name_ALANGUDY,Constituency_Name_ALANGULAM,Constituency_Name_AMBASAMUDRAM,Constituency_Name_AMBATTUR,Constituency_Name_AMBUR,...,Party_VBMP,Party_VCK,Party_VTIP,Party_VTK,Party_VVIP,Party_Valamaana Tamizhagam Katchi,Party_Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi,Party_Vidial Valarchi Perani,Party_WPOI,Party_YSP
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16606,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16607,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16608,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
import pandas as pd
k_ = en_code['Constituency_Name_ACHARAPAKAM'].tolist()
k1_=en_code['Party_VTK'].tolist()
pd=pd.DataFrame({'Cons_name':k_,'party':k1_})
pd

       Cons_name  party
0              0      0
1              0      0
2              0      0
3              0      0
4              0      0
...          ...    ...
16606          0      0
16607          0      0
16608          0      0
16609          0      0
16610          0      0

[16611 rows x 2 columns]